// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXtiN3xkvuaUWITDm1iGpfk4KFiXCKaE',
    appId: '1:757336524733:web:649be3984b8cd47ac534d4',
    messagingSenderId: '757336524733',
    projectId: 'chatapp-756ef',
    authDomain: 'chatapp-756ef.firebaseapp.com',
    storageBucket: 'chatapp-756ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0RacTHR61MZ3ThHesZ_v0nlkB4ZFxgk',
    appId: '1:757336524733:android:80cc98ccc28e0093c534d4',
    messagingSenderId: '757336524733',
    projectId: 'chatapp-756ef',
    storageBucket: 'chatapp-756ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLT4-ykmLiSB0rc7kXt2BpwVHozVayBs',
    appId: '1:757336524733:ios:575bd21c23a507a3c534d4',
    messagingSenderId: '757336524733',
    projectId: 'chatapp-756ef',
    storageBucket: 'chatapp-756ef.firebasestorage.app',
    iosBundleId: 'com.example.gimini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLT4-ykmLiSB0rc7kXt2BpwVHozVayBs',
    appId: '1:757336524733:ios:575bd21c23a507a3c534d4',
    messagingSenderId: '757336524733',
    projectId: 'chatapp-756ef',
    storageBucket: 'chatapp-756ef.firebasestorage.app',
    iosBundleId: 'com.example.gimini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXXtiN3xkvuaUWITDm1iGpfk4KFiXCKaE',
    appId: '1:757336524733:web:68096ab56f7d8b6bc534d4',
    messagingSenderId: '757336524733',
    projectId: 'chatapp-756ef',
    authDomain: 'chatapp-756ef.firebaseapp.com',
    storageBucket: 'chatapp-756ef.firebasestorage.app',
  );
}
